# Generated by Django 3.2.5 on 2021-07-31 12:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('grocery_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('first_name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='grocery_auth.groceryuser')),
                ('products', models.ManyToManyField(blank=True, to='product.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileAddress',
            fields=[
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='profiles.profile')),
                ('street_address', models.CharField(blank=True, max_length=100)),
                ('apartment_number', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('town', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('zip', models.CharField(blank=True, max_length=100)),
                ('address_type', models.CharField(blank=True, choices=[('B', 'Billing'), ('S', 'Shipping')], max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
    ]
