# Generated by Django 3.2.5 on 2021-08-03 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileaddress',
            name='address_type',
        ),
    ]
