# Generated by Django 3.2.5 on 2021-07-27 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210727_1937'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Address',
            new_name='ProfileAddress',
        ),
    ]
