# Generated by Django 3.2.5 on 2021-07-17 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('bakery', 'Bakery'), ('fruits', 'Fruits'), ('vegetables', 'Vegetables'), ('meat', 'Meat'), ('rice and pasta', 'Rice And Pasta'), ('fish and seafood', 'Fish and Seafood'), ('oils, vinegar and dried herbs', 'Oils, Vinegar and Dried Herbs'), ('bear, wine and spirits', 'Bear, Wine and Spirits'), ('soft drinks', 'Soft Drinks'), ('crisps, snacks and nuts', 'Crisps, Snacks and Nuts'), ('chocolate and sweets', 'Chocolate and Sweets'), ('unknown', 'Unknown')], default='UNKNOWN', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('description', models.TextField(max_length=100)),
                ('image', models.ImageField(upload_to='products')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
