# Generated by Django 3.2.5 on 2021-07-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('bakery', 'Bakery'), ('fruits', 'Fruits'), ('vegetables', 'Vegetables'), ('meat', 'Meat'), ('rice and pasta', 'Rice And Pasta'), ('fish and seafood', 'Fish and Seafood'), ('oils, vinegar and dried herbs', 'Oils, Vinegar and Dried Herbs'), ('bear, wine and spirits', 'Bear, Wine and Spirits'), ('soft drinks', 'Soft Drinks'), ('crisps, snacks and nuts', 'crisps, snacks and nuts'), ('chocolate and sweets', 'Sweets'), ('unknown', 'Unknown')], default='UNKNOWN', max_length=60),
        ),
    ]
